# Molecule managed

---
all:
  hosts:
    instance: &id001
      ansible_host: 104.199.126.230
      ansible_port: 22
      ansible_private_key_file: /root/.ssh/google_compute_engine
      ansible_ssh_common_args: -o UserKnownHostsFile=/dev/null -o ControlMaster=auto
        -o ControlPersist=60s -o IdentitiesOnly=yes -o StrictHostKeyChecking=no
      ansible_user: ''
      connection: ssh
ungrouped:
  hosts:
    instance: *id001
  vars: {}
