language: python
python:
- "3.6"
before_install:
- openssl aes-256-cbc -K $encrypted_c0456b90a4ca_key -iv $encrypted_c0456b90a4ca_iv -in .gce_libcloud_auth.enc -out /.gce_libcloud_auth -d 
install:
- pip install ansible==2.3.0 molecule apache-libcloud
env:
- GCE_SERVICE_ACCOUNT_EMAIL='570678884499-compute@developer.gserviceaccount.com'
- GCE_CREDENTIALS_FILE=/.gce_libcloud_auth
- GCE_PROJECT_ID='week-3-178314'
script:
- molecule --debug create
