language: python
python:
- '3.6'
install:
- pip install ansible==2.3.0 molecule apache-libcloud
env:
- GCE_SERVICE_ACCOUNT_EMAIL='570678884499-compute@developer.gserviceaccount.com' GCE_CREDENTIALS_FILE="$(pwd)/.gce_libcloud_auth"
  GCE_PROJECT_ID='week-3-178314'
script:
- pwd
- molecule --debug test
before_install:
- openssl aes-256-cbc -K $encrypted_c0456b90a4ca_key -iv $encrypted_c0456b90a4ca_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mkdir /home/travis/.ssh/
- mv id_rsa_gce /home/travis/.ssh/google_compute_engine
- chmod 0600 /home/travis/.ssh/google_compute_engine
