---
dependency:
  name: galaxy
driver:
  name: gce
  ssh_connection_options:
  - -o ControlPath=~/.ansible/cp/%r@%h-%p
  - -o IdentityFile=/home/travis/build/vitkhab/gce-molecule/id_rsa_gce
  - -o User=molecule
lint:
  name: yamllint
platforms:
  - name: instance
    zone: us-west1-a
    machine_type: f1-micro
    image: debian-8
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
